package fieldauth

import (
	"os"
	"testing"
)

// Runs only when the composed execution config exists (it is generated by
// scripts/compose.sh and gitignored): proves the walker resolves coordinates
// against the real supergraph, including the cross-subgraph entity fields.
func TestRealComposedSchema(t *testing.T) {
	const path = "../../execution-config.json"
	if _, err := os.Stat(path); err != nil {
		t.Skip("execution-config.json not present; run scripts/compose.sh first")
	}

	schema, err := loadClientSchema(path)
	if err != nil {
		t.Fatal(err)
	}

	coords, err := extractCoordinates(`
		query Smoke($id: ID!) {
			title(tconst: $id) {
				primaryTitle
				rating { averageRating numVotes }
				directors { primaryName birthYear }
			}
		}
	`, schema)
	if err != nil {
		t.Fatal(err)
	}

	want := map[string]bool{
		"Query.title":          true,
		"Title.primaryTitle":   true,
		"Title.rating":         true,
		"Rating.averageRating": true,
		"Rating.numVotes":      true,
		"Title.directors":      true,
		"Name.primaryName":     true,
		"Name.birthYear":       true,
	}
	got := map[string]bool{}
	for _, coordinate := range coords {
		got[coordinate] = true
	}
	for coordinate := range want {
		if !got[coordinate] {
			t.Errorf("missing coordinate %q (got %v)", coordinate, coords)
		}
	}
}
