#!/usr/bin/env bash
# Compose the supergraph execution config from the *deployed* subgraphs:
# fetches each subgraph's federated SDL (the same _service.sdl the schema
# files guarantee), generates graph.yaml with the production routing URLs,
# and runs `wgc router compose` to produce execution-config.json.
#
# Single source of truth for subgraph names/URLs lives here.
set -euo pipefail
cd "$(dirname "$0")/.."

WGC_VERSION="0.129.0"
BASE_URL_PATTERN="https://imdb-subgraph-%s-dkuqnmldta-uc.a.run.app/graphql"
SUBGRAPHS=(titles names ratings episodes crew akas principals)

mkdir -p sdl
{
  echo "# GENERATED by scripts/compose.sh — do not edit."
  echo "version: 1"
  echo "subgraphs:"
} > graph.yaml

for name in "${SUBGRAPHS[@]}"; do
  url=$(printf "$BASE_URL_PATTERN" "$name")
  echo "Fetching SDL: $name ($url)"
  sdl=$(curl -sf --retry 3 --retry-all-errors --max-time 60 -X POST "$url" \
    -H 'Content-Type: application/json' \
    -d '{"query":"{ _service { sdl } }"}' | jq -re '.data._service.sdl')
  [ -n "$sdl" ] || { echo "Empty SDL for $name" >&2; exit 1; }
  printf '%s\n' "$sdl" > "sdl/$name.graphql"
  {
    echo "  - name: $name"
    echo "    routing_url: $url"
    echo "    schema:"
    echo "      file: sdl/$name.graphql"
  } >> graph.yaml
done

npx -y "wgc@$WGC_VERSION" router compose -i graph.yaml -o execution-config.json
echo "Wrote execution-config.json"
